version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=saw
      - POSTGRES_USER=dani
      - POSTGRES_PASSWORD=Limoncito1A.
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=Del1al6.
    ports:
      - "5050:80"
